### ISSUE TITLE
Does this still make sense to maintain?

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-embedded-mongo-db#5]
This is more of a existential question, we are in a world of containers, docker, travis, etc, etc... having an embedded mongo can be easily added to a test on any CI platform or run a matrix of versions of mongo using docker.

**Comment by michel-kraemer** [comment]
Paulo,

It's always useful to be able to execute unit tests locally without the burden of setting up a test infrastructure or running MongoDB in a Docker container upfront. Of course, Docker is really easy to use, but it's even easier to just press the Run button in your IDE or execute 'mvn test'.

Also, if you want a clean database for each unit test you don't have to restart the Docker container all the time. I'm mostly using de.flapdoodle.embed.mongo for this. I haven't used vert-x3/vertx-embedded-mongo-db yet. I don't know the differences, but I agree with you that the functionality of vert-x3/vertx-embedded-mongo-db is covered by other tools.

Michel

**Comment by pmlopes** [comment]
@michel-kraemer I agree that is my point, for example one can delegate to flapdoodle itself to achive the same functionality or use something more generic such as:

https://www.testcontainers.org/

I just see that this component does not bring any added value (i might be missing something, that is why I started this discussion) and that we will end up having to maintain it for some very rare use case out there...

**Comment by karianna** [comment]
@johnoliver Hmm, not sure we even use this anymore...?

**Comment by jo5ef** [comment]
We're using it in our projects and find it useful : )

**Comment by vietj** [comment]
@karianna is it used in mongo tests ?

**Comment by karianna** [comment]
It's still used by the Mongo client tests yes, so let's keep it for now.

**Comment by vietj** [comment]
I'm not against dropping it, perhaps this should be moved to an alternative thing later

**Comment by vietj** [comment]
but at the age of containers indeed, it's a good question
