### ISSUE TITLE
Vert.x 4 removal

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-embedded-mongo-db#9]
This module is not longer supported in Vert.x 4

**Comment by jo5ef** [comment]
[vertx-wiremongo](https://github.com/NoEnv/vertx-wiremongo) may be an alternative

**Comment by vietj** [comment]
can you do a PR on the https://github.com/vert-x3/vertx-4-migration-guide
to add this ?

**Comment by jo5ef** [comment]
sure, done
